# Generated by Django 5.1.6 on 2025-03-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
    ]
