# Generated by Django 5.1.6 on 2025-03-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_api', '0002_remove_subject_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastquestion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='past_questions/'),
        ),
    ]
