# Generated by Django 5.1.6 on 2025-03-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_api', '0002_alter_semester_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('semester', 'code')},
        ),
    ]
