# Generated by Django 5.1.6 on 2025-03-04 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_api', '0004_alter_pastquestion_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('subject', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('chapter', 'title')},
        ),
    ]
