# Generated by Django 5.1.6 on 2025-07-23 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_api', '0005_alter_chapter_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='syllabus_api.semester'),
        ),
    ]
