# Generated by Django 5.1.6 on 2025-07-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_api', '0006_alter_subject_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='content',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='references',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='syllabus_files/'),
        ),
    ]
